var list_t2 = [
"1,2층 사이의 계단_Stairs between first and second floor",
"2,3층 사이의 계단_Stairs between second and third floor",
"라운지_Lounge",
"개인물품보관함_Locker",
"디지털자료실_Digital data room",
"출입구_Gate",
"조리실_Kitchen",
"개인물품보관함을 정리하는 소리_Sound from while cleaning up locker",
"손건조기_Hand drier",
"안내소_Information desk",
"쉼터(1)_Rest area(1)", 
"쉼터(2)_Rest area(2)",
"시각장애인실의 환풍기_Over the ventilating fan at the room for visually handicapped",
"무인식권발매기_Kiosk",
"구내식당(1)_Cafeteria(1)", 
"구내식당(2)_Cafeteria(2)",
"어린이열람실_Children's Reading Room",
"엘리베이터_Elevator",
"열람실_Reading room",
"무인 대출 반납기_Self service book return machine",
"자판기(1)_Vending machine(1)",
"자판기(2)_Vending machine(2)",
"젓가락_Chopsticks",
"정기간행물실_Periodicals room",
"정수기_Water purifier",
"종합자료실_General collection room",
"좌석 예약 시스템(1)_Seat Reservation System(1)",
"좌석 예약 시스템(2)_Seat Reservation System(2)",
"종합자료실 앞 복도_Hallway in front of reference room",
"시청각실_Audiovisual room",
"지하로 내려가는 계단_Stair to first basement level"
];
